
networks:
    dev-network:
      driver: bridge

services:
  api_prod:
    image: achabazam/personal_repo:api_prod
    ports:
      - "8888:80"
    networks:
      - dev-network


  web_prod:
    image: achabazam/personal_repo:web_prod
    ports:
      - "3333:3000"
    networks:
      - dev-network
    environment:
      - API_DEV_IP=api_prod
      - API_URL=http://api_prod:80